### ISSUE TITLE
Dev2 branch running maingame scene not working

### ISSUE THREAD

**Issue by warglaivez** [thesecretlab/NonCombativeFPS#23]
Dev2 31/08

Summary
Game runs on play for about 2 seconds before closing. 

Steps

    Open unity
    load scene
    Click start button to run game.

Expected Result
Everything works

Actual Result
Game only runs for  seconds before closing. 

Extra Information
console information: 
IndexOutOfRangeException: Array index is out of range.
Ship.setPower (Boolean power) (at Assets/Scripts/Util/Ship.cs:86)
Reactor.onBreak () (at Assets/Scripts/Breaker/Reactor.cs:10)
BreakEvent.dobreak () (at Assets/Scripts/Util/BreakEvent.cs:26)
Ship.tryBreak () (at Assets/Scripts/Util/Ship.cs:101)

**Comment by jpalbion** [comment]
Please use the template

Branch & date
Master 31/8

Summary
What is wrong

Steps
1. Open unity
2. load scene
3. ect

Expected Result
Everything works

Actual Result
Nothing Works

Extra Information
Anything else

**Comment by jpalbion** [comment]
Found problem with naming clash with identifying Light objects. to prevent further issues avoid using flourolight and floodlight in names
